`use strict`
const imgs = [
https://www.tarotcardmeanings.net/images/tarotcards/tarot-fool.jpg
https://www.tarotcardmeanings.net/images/tarotcards/tarot-magician.jpg
https://www.tarotcardmeanings.net/images/tarotcards/tarot-highpriestess.jpg
https://www.tarotcardmeanings.net/images/tarotcards/tarot-empress.jpg
https://www.tarotcardmeanings.net/images/tarotcards/tarot-emperor.jpg
https://www.tarotcardmeanings.net/images/tarotcards/tarot-hierophant.jpg
https://www.tarotcardmeanings.net/images/tarotcards/tarot-lovers.jpg
https://www.tarotcardmeanings.net/images/tarotcards/tarot-chariot.jpg
https://www.tarotcardmeanings.net/images/tarotcards/tarot-strength.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-hermit.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wheeloffortune.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-justice.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-hangedman.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-death.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-temperance.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-devil.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-tower.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-star.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-moon.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-sun.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-judgement.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-world.jpg


https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-01.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-02.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-03.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-04.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-05.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-06.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-07.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-08.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-09.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-10.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-11.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-12.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-13.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-wands-14.jpg

https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-01.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-02.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-03.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-04.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-05.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-06.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-07.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-08.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-09.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-10.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-11.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-12.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-13.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-pentacles-14.jpg

https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-01.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-02.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-03.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-04.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-05.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-06.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-07.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-08.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-09.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-10.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-11.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-12.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-13.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-cups-14.jpg

https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-01.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-02.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-03.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-04.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-05.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-06.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-07.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-08.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-09.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-10.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-11.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-12.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-13.jpg
https://www.tarotcardmeanings.net/images/tarotcards120px/tarot-swords-14.jpg
]
